//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSystemHelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ConsultaU
    {
        public string NOME_USUARIO { get; set; }
        public int ID_CHAMADO { get; set; }
        public string CHAMADO { get; set; }
        public Nullable<System.DateTime> DATA_CRIACAO_CHAMADO { get; set; }
        public Nullable<System.DateTime> DATA_FINALIZACAO_CHAMADO { get; set; }
        public string STATUS_CHAMADO { get; set; }
        public string TECNICO { get; set; }
    }
}
