//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSystemHelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class US_CHAMADOS
    {
        public int ID_CHAMADO { get; set; }
        public string CHAMADO { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DATA_CRIACAO_CHAMADO { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DATA_INICIO_SUPORTE { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DATA_FINALIZACAO_CHAMADO { get; set; }
        public string SOLUCAO { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<int> ID_USUARIOS_RESP { get; set; }
        public Nullable<int> ID_EQUIPAMENTO { get; set; }
        public Nullable<int> ID_STATUS_CHAMADO { get; set; }
    
        public virtual US_EQUIPAMENTO US_EQUIPAMENTO { get; set; }
        public virtual US_STATUS US_STATUS { get; set; }
        public virtual US_USUARIOS US_USUARIOS { get; set; }
    }
}
