//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSystemHelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class US_STATUS
    {
        public US_STATUS()
        {
            this.US_CHAMADOS = new HashSet<US_CHAMADOS>();
        }
    
        public int ID_STATUS_CHAMADO { get; set; }
        public string STATUS_CHAMADO { get; set; }
    
        public virtual ICollection<US_CHAMADOS> US_CHAMADOS { get; set; }
    }
}
