//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSystemHelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class US_TIPO_EQUIPAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public US_TIPO_EQUIPAMENTO()
        {
            this.US_EQUIPAMENTO = new HashSet<US_EQUIPAMENTO>();
        }
    
        public int ID_TIPO_EQUIPAMENTO { get; set; }
        public string TIPO_EQUIPAMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<US_EQUIPAMENTO> US_EQUIPAMENTO { get; set; }
    }
}
