//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSystemHelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class US_USUARIOS
    {
        public US_USUARIOS()
        {
            this.US_CHAMADOS = new HashSet<US_CHAMADOS>();
        }
    
        public int ID_USUARIOS { get; set; }
        public string NOME_USUARIO { get; set; }
        [Required(ErrorMessage = "Por favor, informe seu usuário!")]
        [Display(Name = "Informe seu usuário!")]
        public string EMAIL_USUARIO { get; set; }
        [Required(ErrorMessage="Por favor, informe sua senha!")]
        [Display(Name="Informe sua senha!")]
        [DataType(DataType.Password)]
        public string SENHA_USUARIO { get; set; }
        public Nullable<int> ID_TIPO_USUARIO { get; set; }
        public Nullable<int> ID_SETOR { get; set; }
    
        public virtual ICollection<US_CHAMADOS> US_CHAMADOS { get; set; }
        public virtual US_SETORES US_SETORES { get; set; }
        public virtual US_TIPO_USUARIO US_TIPO_USUARIO { get; set; }
    }
}
