CREATE DATABASE BDUniSystemHelpDesk

GO

USE BDUniSystemHelpDesk

GO

CREATE TABLE US_TIPO_USUARIO
(ID_TIPO_USUARIO INT IDENTITY PRIMARY KEY,
TIPO_USUARIO VARCHAR(25) NOT NULL);

GO

CREATE TABLE US_SETORES
(ID_SETOR INT IDENTITY PRIMARY KEY,
SETOR VARCHAR (15) NOT NULL);

GO

CREATE TABLE US_USUARIOS
(ID_USUARIOS INT IDENTITY PRIMARY KEY,
NOME_USUARIO VARCHAR (50) NOT NULL,
EMAIL_USUARIO VARCHAR (50) NOT NULL,
SENHA_USUARIO VARCHAR (50) NOT NULL,

ID_TIPO_USUARIO INT,
ID_SETOR INT,

FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES US_TIPO_USUARIO,
FOREIGN KEY (ID_SETOR) REFERENCES US_SETORES  
);

GO

CREATE TABLE US_TIPO_EQUIPAMENTO
(ID_TIPO_EQUIPAMENTO INT IDENTITY PRIMARY KEY,
TIPO_EQUIPAMENTO VARCHAR(30) NOT NULL,
);

GO

CREATE TABLE US_EQUIPAMENTO
(ID_EQUIPAMENTO INT IDENTITY PRIMARY KEY,
EQUIPAMENTO VARCHAR (50) NOT NULL,
PRIORIDADE INT NOT NULL,

ID_TIPO_EQUIPAMENTO INT,

FOREIGN KEY (ID_TIPO_EQUIPAMENTO) REFERENCES US_TIPO_EQUIPAMENTO
);

GO

CREATE TABLE US_STATUS
(ID_STATUS_CHAMADO INT IDENTITY PRIMARY KEY,
STATUS_CHAMADO VARCHAR(20) NOT NULL, 
);

GO

CREATE TABLE US_TECNICO
(ID_TECNICO INT IDENTITY PRIMARY KEY,
TECNICO VARCHAR (30)
);
GO

CREATE TABLE US_CHAMADOS
(ID_CHAMADO INT IDENTITY PRIMARY KEY,
CHAMADO VARCHAR (255),
DATA_CRIACAO_CHAMADO DATE,
DATA_INICIO_SUPORTE DATE,
DATA_FINALIZACAO_CHAMADO DATE,
SOLUCAO VARCHAR (255),
COMENTARIOS VARCHAR(50),

ID_USUARIOS_RESP INT,
ID_EQUIPAMENTO INT,
ID_STATUS_CHAMADO INT,
ID_TECNICO INT,

FOREIGN KEY (ID_USUARIOS_RESP) REFERENCES US_USUARIOS,
FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES US_EQUIPAMENTO,
FOREIGN KEY (ID_STATUS_CHAMADO) REFERENCES US_STATUS, 
FOREIGN KEY (ID_TECNICO) REFERENCES US_TECNICO
);
go
--INSERT INTO US_SETORES (SETOR)VALUES('Gerência'),('Administração'),('Contabilidade'),('RH'),('RM'),('CheckOut'),('Recepção'),('Televendas'),('Prevenção'),('Comercial');
--go
--INSERT INTO US_TIPO_USUARIO (TIPO_USUARIO)VALUES('Usuário'),('Administrador');
--go
--INSERT INTO US_TIPO_EQUIPAMENTO (TIPO_EQUIPAMENTO)VALUES('Hardware'),('Telefonia'),('Software'),('Rede');
--go
--SELECT * FROM US_EQUIPAMENTO
--go
--INSERT INTO US_EQUIPAMENTO(EQUIPAMENTO,PRIORIDADE,ID_TIPO_EQUIPAMENTO)VALUES('Desktop','3','1'),('Notebook','3','1'),('Impressora','4','1'),('Switch','5','4'),('Modem/Roteador','5','4'),('Servidor','5','1'),('Ramal/PABX','3','2'),('Office','2','3'),('Sistema Interno','5','3'),('Sistema PDVs','5','3'),('Login/Senha','1','3')
--go
--INSERT INTO US_STATUS(STATUS_CHAMADO)VALUES('Aberto'),('Em Atendimento'),('Fechado')