//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSystemHelpDeskWPF.WebServiceUS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaU", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ConsultaU : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOME_USUARIOField;
        
        private int ID_CHAMADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CHAMADOField;
        
        private System.Nullable<System.DateTime> DATA_CRIACAO_CHAMADOField;
        
        private System.Nullable<System.DateTime> DATA_FINALIZACAO_CHAMADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUS_CHAMADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TECNICOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NOME_USUARIO {
            get {
                return this.NOME_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOME_USUARIOField, value) != true)) {
                    this.NOME_USUARIOField = value;
                    this.RaisePropertyChanged("NOME_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ID_CHAMADO {
            get {
                return this.ID_CHAMADOField;
            }
            set {
                if ((this.ID_CHAMADOField.Equals(value) != true)) {
                    this.ID_CHAMADOField = value;
                    this.RaisePropertyChanged("ID_CHAMADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CHAMADO {
            get {
                return this.CHAMADOField;
            }
            set {
                if ((object.ReferenceEquals(this.CHAMADOField, value) != true)) {
                    this.CHAMADOField = value;
                    this.RaisePropertyChanged("CHAMADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> DATA_CRIACAO_CHAMADO {
            get {
                return this.DATA_CRIACAO_CHAMADOField;
            }
            set {
                if ((this.DATA_CRIACAO_CHAMADOField.Equals(value) != true)) {
                    this.DATA_CRIACAO_CHAMADOField = value;
                    this.RaisePropertyChanged("DATA_CRIACAO_CHAMADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> DATA_FINALIZACAO_CHAMADO {
            get {
                return this.DATA_FINALIZACAO_CHAMADOField;
            }
            set {
                if ((this.DATA_FINALIZACAO_CHAMADOField.Equals(value) != true)) {
                    this.DATA_FINALIZACAO_CHAMADOField = value;
                    this.RaisePropertyChanged("DATA_FINALIZACAO_CHAMADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string STATUS_CHAMADO {
            get {
                return this.STATUS_CHAMADOField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUS_CHAMADOField, value) != true)) {
                    this.STATUS_CHAMADOField = value;
                    this.RaisePropertyChanged("STATUS_CHAMADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TECNICO {
            get {
                return this.TECNICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TECNICOField, value) != true)) {
                    this.TECNICOField = value;
                    this.RaisePropertyChanged("TECNICO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceUS.WebServiceUSSoap")]
    public interface WebServiceUSSoap {
        
        // CODEGEN: Generating message contract since element name ConsultarChamadoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarChamado", ReplyAction="*")]
        UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoResponse ConsultarChamado(UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarChamado", ReplyAction="*")]
        System.Threading.Tasks.Task<UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoResponse> ConsultarChamadoAsync(UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarChamadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarChamado", Namespace="http://tempuri.org/", Order=0)]
        public UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequestBody Body;
        
        public ConsultarChamadoRequest() {
        }
        
        public ConsultarChamadoRequest(UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarChamadoRequestBody {
        
        public ConsultarChamadoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarChamadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarChamadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoResponseBody Body;
        
        public ConsultarChamadoResponse() {
        }
        
        public ConsultarChamadoResponse(UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarChamadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UniSystemHelpDeskWPF.WebServiceUS.ConsultaU[] ConsultarChamadoResult;
        
        public ConsultarChamadoResponseBody() {
        }
        
        public ConsultarChamadoResponseBody(UniSystemHelpDeskWPF.WebServiceUS.ConsultaU[] ConsultarChamadoResult) {
            this.ConsultarChamadoResult = ConsultarChamadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUSSoapChannel : UniSystemHelpDeskWPF.WebServiceUS.WebServiceUSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUSSoapClient : System.ServiceModel.ClientBase<UniSystemHelpDeskWPF.WebServiceUS.WebServiceUSSoap>, UniSystemHelpDeskWPF.WebServiceUS.WebServiceUSSoap {
        
        public WebServiceUSSoapClient() {
        }
        
        public WebServiceUSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoResponse UniSystemHelpDeskWPF.WebServiceUS.WebServiceUSSoap.ConsultarChamado(UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequest request) {
            return base.Channel.ConsultarChamado(request);
        }
        
        public UniSystemHelpDeskWPF.WebServiceUS.ConsultaU[] ConsultarChamado() {
            UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequest inValue = new UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequest();
            inValue.Body = new UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequestBody();
            UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoResponse retVal = ((UniSystemHelpDeskWPF.WebServiceUS.WebServiceUSSoap)(this)).ConsultarChamado(inValue);
            return retVal.Body.ConsultarChamadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoResponse> UniSystemHelpDeskWPF.WebServiceUS.WebServiceUSSoap.ConsultarChamadoAsync(UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequest request) {
            return base.Channel.ConsultarChamadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoResponse> ConsultarChamadoAsync() {
            UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequest inValue = new UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequest();
            inValue.Body = new UniSystemHelpDeskWPF.WebServiceUS.ConsultarChamadoRequestBody();
            return ((UniSystemHelpDeskWPF.WebServiceUS.WebServiceUSSoap)(this)).ConsultarChamadoAsync(inValue);
        }
    }
}
